"""Compile editable JSON vocabularies into allocation-free C++ lookup tables.

The generated header is committed. Building the library therefore needs neither Python nor JSON
parsing; this tool is run only when the alias JSON changes.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def quoted(value: str) -> str:
    escaped = (value.replace("\\", "\\\\").replace('"', '\\"')
               .replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t"))
    return f'"{escaped}"'


def load(path: Path):
    with path.open("r", encoding="utf-8") as stream:
        return json.load(stream)


def require_unique(values: list[str], what: str) -> None:
    duplicates = sorted({value for value in values if values.count(value) > 1})
    if duplicates:
        raise ValueError(f"duplicate {what}: {', '.join(duplicates)}")


def generate(source: Path) -> str:
    platforms: dict[str, str] = load(source / "platforms.json")
    container_groups: dict[str, list[str]] = load(source / "containers.json")
    languages: list[dict[str, object]] = load(source / "languages.json")
    rejected_groups: list[str] = load(source / "rejected_groups.json")

    platform_rows = sorted(platforms.items())
    require_unique([key for key, _ in platform_rows], "platform alias")

    container_rows: list[tuple[str, str]] = []
    for medium, extensions in container_groups.items():
        container_rows.extend((extension, medium) for extension in extensions)
    container_rows.sort()
    require_unique([extension for extension, _ in container_rows], "container extension")

    require_unique(rejected_groups, "rejected group token")
    rejected_groups.sort()
    for entry in languages:
        if set(entry) != {"expression", "code"}:
            raise ValueError(f"invalid language row: {entry!r}")

    lines = [
        "// Generated by tools/generate_aliases.py; do not edit.",
        "#pragma once",
        "#include <array>",
        "#include <string_view>",
        "",
        "namespace neurelease::convert::generated {",
        "struct Alias { std::string_view input; std::string_view output; };",
        "struct LanguageAlias { std::string_view expression; std::string_view code; };",
        "",
        f"inline constexpr std::array<Alias, {len(platform_rows)}> platformAliases{{{{",
    ]
    lines.extend(f"    {{{quoted(key)}, {quoted(value)}}}," for key, value in platform_rows)
    lines.extend(["}};", "", f"inline constexpr std::array<Alias, {len(container_rows)}> containers{{{{"])
    lines.extend(f"    {{{quoted(extension)}, {quoted(medium)}}},"
                 for extension, medium in container_rows)
    lines.extend(["}};", "", f"inline constexpr std::array<LanguageAlias, {len(languages)}> languages{{{{"])
    lines.extend(
        f"    {{{quoted(str(row['expression']))}, {quoted(str(row['code']))}}},"
        for row in languages
    )
    lines.extend(["}};", "", f"inline constexpr std::array<std::string_view, {len(rejected_groups)}> rejectedGroups{{{{"])
    lines.extend(f"    {quoted(value)}," for value in rejected_groups)
    lines.extend(["}};", "", "} // namespace neurelease::convert::generated", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, default=Path("data/aliases"))
    parser.add_argument("--output", type=Path,
                        default=Path("src/convert/generated/aliases.hpp"))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    output = generate(args.source)
    if args.check:
        current = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if current != output:
            raise SystemExit(f"generated alias tables are stale: run {Path(__file__).name}")
        return
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
